# -*- coding: utf-8 -*-
"""fire_combined.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RmyRWoepi1F0JF0LRjDqlSx-OsIAspNr
"""

!pip install ultralytics -q

# ═══════════════════════════════════════════════════════════════
# CELL 1 — Install YOLOv8  (run EVERY time)
# ═══════════════════════════════════════════════════════════════
!pip install ultralytics -q

import torch
print(f'PyTorch: {torch.__version__}')
print(f'CUDA: {torch.cuda.is_available()}')
if torch.cuda.is_available():
    print(f'✅ GPU: {torch.cuda.get_device_name(0)}')
else:
    print('⚠️  No GPU! Go to Runtime → Change runtime type → T4 GPU')

# ═══════════════════════════════════════════════════════════════
# CELL 2 — Mount Google Drive  (run EVERY time)
# ═══════════════════════════════════════════════════════════════
from google.colab import drive
drive.mount('/content/drive')

import os
DRIVE_DIR = '/content/drive/MyDrive/fire_detection'
os.makedirs(DRIVE_DIR, exist_ok=True)
print(f'✅ Google Drive mounted!')
print(f'📁 Save directory: {DRIVE_DIR}')

# ═══════════════════════════════════════════════════════════════
# CELL 3 — Extract Dataset  (run EVERY time)
# ═══════════════════════════════════════════════════════════════
import os

zip_path = '/content/drive/MyDrive/fire_combined.zip'

if not os.path.exists('/content/data/fire_combined/data.yaml'):
    print('📦 Extracting dataset...')
    !unzip -q {zip_path} -d /content/
    print('✅ Dataset extracted!')
else:
    print('✅ Dataset already extracted, skipping.')

!ls /content/data/fire_combined/

# ═══════════════════════════════════════════════════════════════
# CELL 4 — Fix data.yaml paths for Colab  (run EVERY time)
# ═══════════════════════════════════════════════════════════════
import yaml

data_yaml = {
    'train': '/content/data/fire_combined/train/images',
    'val':   '/content/data/fire_combined/valid/images',
    'test':  '/content/data/fire_combined/test/images',
    'nc': 10,
    'names': ['Ates', 'Fire', 'Fire Detection', 'api',
              'car-crash', 'fight', 'knife', 'no-fight', 'pistol', 'smoke']
}

with open('/content/data/fire_combined/data.yaml', 'w') as f:
    yaml.dump(data_yaml, f, default_flow_style=False)

print('✅ data.yaml fixed for Colab paths!')
with open('/content/data/fire_combined/data.yaml', 'r') as f:
    print(f.read())

# ═══════════════════════════════════════════════════════════════
# CELL 4 — Fix data.yaml paths for Colab  (run EVERY time)
# ═══════════════════════════════════════════════════════════════
import yaml

data_yaml = {
    'train': '/content/data/fire_combined/train/images',
    'val':   '/content/data/fire_combined/valid/images',
    'test':  '/content/data/fire_combined/test/images',
    'nc': 1,
    'names': ['Fire']
}

with open('/content/data/fire_combined/data.yaml', 'w') as f:
    yaml.dump(data_yaml, f, default_flow_style=False)

print('✅ data.yaml fixed for Colab paths!')
with open('/content/data/fire_combined/data.yaml', 'r') as f:
    print(f.read())

# ═══════════════════════════════════════════════════════════════
# CELL 5 — TRAIN  🔥  (First time only)
# Auto-saves checkpoint to Drive every 5 epochs.
# If session expires → skip this cell, run CELL 6 (RESUME) instead.
# ═══════════════════════════════════════════════════════════════
from ultralytics import YOLO
import shutil, os, glob

DRIVE_DIR = '/content/drive/MyDrive/fire_detection'

# Count images
train_imgs = len(glob.glob('/content/data/fire_combined/train/images/*.*'))
valid_imgs = len(glob.glob('/content/data/fire_combined/valid/images/*.*'))
test_imgs  = len(glob.glob('/content/data/fire_combined/test/images/*.*'))
print(f'📊 Train: {train_imgs} | Valid: {valid_imgs} | Test: {
    test_imgs}')

# ── Auto-backup callback ─────────────────────────────────────────
def backup_to_drive(trainer):
    """Saves checkpoint to Drive every 5 epochs automatically."""
    epoch = trainer.epoch + 1
    if epoch % 5 == 0:
        src_last = '/content/runs/fire_model/weights/last.pt'
        src_best = '/content/runs/fire_model/weights/best.pt'
        src_csv  = '/content/runs/fire_model/results.csv'
        if os.path.exists(src_last):
            shutil.copy(src_last, f'{DRIVE_DIR}/last.pt')
            shutil.copy(src_last, f'{DRIVE_DIR}/checkpoint_epoch{epoch}.pt')
            print(f'\n💾 [Epoch {epoch}] Checkpoint saved to Drive!')
        if os.path.exists(src_best):
            shutil.copy(src_best, f'{DRIVE_DIR}/best.pt')
        if os.path.exists(src_csv):
            shutil.copy(src_csv, f'{DRIVE_DIR}/results.csv')

# ── Train ────────────────────────────────────────────────────────
model = YOLO('yolov8n.pt')
model.add_callback('on_train_epoch_end', backup_to_drive)

print('🔥 Starting training (50 epochs, auto-stop if no improvement for 10 epochs)...')
results = model.train(
    data='/content/data/fire_combined/data.yaml',
    epochs=50,
    batch=16,
    imgsz=640,
    device=0,
    save_period=5,
    patience=10,
    project='/content/runs',
    name='fire_model',
    exist_ok=True
)
print('\n✅ Training complete!')

# ═══════════════════════════════════════════════════════════════
# CELL 6 — RESUME after session expired  🔄
# Run this INSTEAD of Cell 5 after a session expires.
# Run this same cell every time it expires — no matter how many times!
# ═══════════════════════════════════════════════════════════════
from ultralytics import YOLO
import shutil, os

DRIVE_DIR = '/content/drive/MyDrive/fire_detection'

# Step 1: Restore last checkpoint from Drive
os.makedirs('/content/runs/fire_model/weights', exist_ok=True)
last_ckpt = f'{DRIVE_DIR}/last.pt'

if not os.path.exists(last_ckpt):
    print('❌ No checkpoint found in Drive!')
    print('   Run Cell 5 (TRAIN) instead — training has not started yet.')
else:
    shutil.copy(last_ckpt, '/content/runs/fire_model/weights/last.pt')
    print('✅ Checkpoint restored from Drive!')

    # Step 2: Auto-backup callback (same as training cell)
    def backup_to_drive(trainer):
        epoch = trainer.epoch + 1
        if epoch % 5 == 0:
            src_last = '/content/runs/fire_model/weights/last.pt'
            src_best = '/content/runs/fire_model/weights/best.pt'
            src_csv  = '/content/runs/fire_model/results.csv'
            if os.path.exists(src_last):
                shutil.copy(src_last, f'{DRIVE_DIR}/last.pt')
                shutil.copy(src_last, f'{DRIVE_DIR}/checkpoint_epoch{epoch}.pt')
                print(f'\n💾 [Epoch {epoch}] Checkpoint saved to Drive!')
            if os.path.exists(src_best):
                shutil.copy(src_best, f'{DRIVE_DIR}/best.pt')
            if os.path.exists(src_csv):
                shutil.copy(src_csv, f'{DRIVE_DIR}/results.csv')

    # Step 3: Resume!
    print('🔄 Resuming training from last checkpoint...')
    model = YOLO('/content/runs/fire_model/weights/last.pt')
    model.add_callback('on_train_epoch_end', backup_to_drive)

    results = model.train(
        data='/content/data/fire_combined/data.yaml',
        epochs=50,
        batch=16,
        imgsz=640,
        device=0,
        patience=10,
        project='/content/runs',
        name='fire_model',
        exist_ok=True,
        resume=True
    )
    print('\n✅ Training complete!')

# ═══════════════════════════════════════════════════════════════
# CELL 7 — FINAL SAVE to Drive  💾
# Run this AFTER training completes (Cell 5 or Cell 6 finishes).
# ═══════════════════════════════════════════════════════════════
import shutil, os, glob

DRIVE_DIR = '/content/drive/MyDrive/fire_detection'
os.makedirs(DRIVE_DIR, exist_ok=True)

src = '/content/runs/fire_model'

# Save model weights
shutil.copy(f'{src}/weights/best.pt', f'{DRIVE_DIR}/best_final.pt')
shutil.copy(f'{src}/weights/last.pt', f'{DRIVE_DIR}/last_final.pt')
print('✅ Saved: best_final.pt')
print('✅ Saved: last_final.pt')

# Save results.csv (needed for IEEE graphs!)
shutil.copy(f'{src}/results.csv', f'{DRIVE_DIR}/results.csv')
print('✅ Saved: results.csv  ← for IEEE graphs!')

# Save all training plots
plots = glob.glob(f'{src}/*.png') + glob.glob(f'{src}/*.jpg')
os.makedirs(f'{DRIVE_DIR}/plots', exist_ok=True)
for p in plots:
    shutil.copy(p, f'{DRIVE_DIR}/plots/{os.path.basename(p)}')
print(f'✅ Saved: {len(plots)} training plots → plots/ folder')

print('\n📁 Everything saved to: MyDrive/fire_detection/')
print('   ├── best_final.pt')
print('   ├── last_final.pt')
print('   ├── results.csv        ← open with IEEE.ipynb for graphs')
print('   └── plots/')

